apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: 080266302756.dkr.ecr.us-east-2.amazonaws.com/flask_rest:cac68fc1fe320e0c0c2e0721e8d1f0f41a477bc3
        name: flask
        envFrom:
          - secretRef:
              name: flask-app-sm
          - secretRef:
              name: flask-app-ssm
        ports:
        - containerPort: 5000
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"