# using secrets manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-sm
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: rdssecret
      metadataPolicy: None
      property: username
    secretKey: DB_USERNAME
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: rdssecret
      metadataPolicy: None
      property: password
    secretKey: DB_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: flask-app-sm
--- 
# using ssm
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-ssm
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /db/endpoint
      metadataPolicy: None
    secretKey: DB_HOST
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None #Auto
      key: /db/dbname
      metadataPolicy: None
    secretKey: DB_DATABASE
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: flask-app-ssm
